name: 'Release Documentation'
description: 'Create a release documentation from the repository PRs'
branding:
  icon: 'file-text'  
  color: 'red'
inputs:
  token:
    required: true
    description: "GitHub Access Token"
  latest:
    required: true
    description: "the latest tag for which this release documentation is meant for"
  template:  # id of input
    description: "The mustache template which should be used to render the release documentation"
    required: false
    default: |
      # What's Changed
      <!-- Features & Enhancements -->
      {{#pull_requests.feature.length}}
      ## 🚀 Features & Enhancements
      {{#pull_requests.feature}}
      * {{ title }}, #{{ number }} by @{{ author }}
      {{/pull_requests.feature}}
      {{/pull_requests.feature.length}}
      <!-- Documentation -->
      {{#pull_requests.documentation.length}}
      ## 📖 Documentation
      {{#pull_requests.documentation}}
      * {{ title }}, #{{ number }} by @{{ author }}
      {{/pull_requests.documentation}}
      {{/pull_requests.documentation.length}}
      <!-- Housekeeping -->
      {{#pull_requests.housekeeping.length}}
      ## 🧹 Housekeeping
      {{#pull_requests.housekeeping}}
      * {{ title }}, #{{ number }} by @{{ author }}
      {{/pull_requests.housekeeping}}
      {{/pull_requests.housekeeping.length}}
      <!-- Dependency updates -->
      {{#pull_requests.dependencies.length}}
      ## 📦 Dependency updates
      {{#pull_requests.dependencies}}
      * {{ title }}, #{{ number }} by @{{ author }}
      {{/pull_requests.dependencies}}
      {{/pull_requests.dependencies.length}}
outputs:
  content:
    description: 'The parsed template filled with PRs'
runs:
  using: 'node12'
  main: 'out/index.js'
