name: 'Release Documentation'
description: 'Create a release documentation from the repository PRs'
inputs:
  token:
    required: true
    description: "GitHub Access Token"
  latest:
    required: true
    description: "the latest tag for which this release documentation is meant for"
  template:  # id of input
    description: "The ninja template which should be used to render the release documentation"
    required: false
    default: |
      # What's Changed
      ## 🚀 Features & Enhancements
      {% for item in pull_requests["features"] %}
      * {{ item }}
      {% endfor %}
      ## 📖 Documentation
      {% for item in pull_requests["documentation"] %}
      * {{ item }}
      {% endfor %}
      ## 🧹 Housekeeping
      {% for item in pull_requests["housekeeping"] %}
      * {{ item }}
      {% endfor %}
      ## 📦 Dependency updates
      {% for item in pull_requests["dependencies"] %}
      * {{ item }}
      {% endfor %}
outputs:
  content:
    description: 'The parsed template filled with PRs'
runs:
  using: 'node12'
  main: 'out/index.js'
