name: 'Release Documentation'
description: 'Create a release documentation from the repository PRs'
inputs:
  token:
    required: true
    description: "GitHub Access Token"
  latest:
    required: true
    description: "the latest tag for which this release documentation is meant for"
  template:  # id of input
    description: "The ninja template which should be used to render the release documentation"
    required: false
    default: |
      # What's Changed
      ## 🚀 Features & Enhancements
      {{#pull_requests.features}}
      * {{ title }} PR: #{{ number }}
      {{/pull_requests.features}}
      ## 📖 Documentation
      {{#pull_requests.documentation}}
      * {{ title }} PR: #{{ number }}
      {{/pull_requests.documentation}}
      ## 🧹 Housekeeping
      {{#pull_requests.housekeeping}}
      * {{ title }} PR: #{{ number }}
      {{/pull_requests.housekeeping}}
      ## 📦 Dependency updates
      {{#pull_requests.dependencies}}
      * {{ title }} PR: #{{ number }}
      {{/pull_requests.dependencies}}
outputs:
  content:
    description: 'The parsed template filled with PRs'
runs:
  using: 'node12'
  main: 'out/index.js'
